### ISSUE TITLE
"Add a computer player" button makes the client freeze. 

### ISSUE THREAD

**Issue by anyaeats160carrots** [Bipsy/Catan-Client#108]
Right now, "Add a computer player" button in the waiting view makes the client freeze. It should be either disabled, since we don't have AI's, or deleted, or should do nothing.

**Comment by anyaeats160carrots** [comment]
Just saw that it unfreezes eventually and throws an error. Apparently, it's making an addAI server call that we don't implement

**Comment by Seiji42** [comment]
This would be an issue on the server side.

**Comment by anyaeats160carrots** [comment]
I already disabled it in the client.
