### ISSUE TITLE
Double-check that we need to display the number of resource cards in robView

### ISSUE THREAD

**Issue by anyaeats160carrots** [Bipsy/Catan-Client#98]
We decided to display player's number of resource card, but the spec says to display the number of devCards. We should double-check that we're right

**Comment by Seiji42** [comment]
In the game, you don't rob dev cards. You rob resource cards. I'm fairly positive we don't care about the number of dev cards a player has.

**Comment by anyaeats160carrots** [comment]
That's my impression too, looks like the spec has a mistake
